package fakearray

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/sanderdescamps/go-pure-flasharray/pkg/flashclient"
)

var ErrExportOnInvalidPath = errors.New("export on invalid path")

func allExporters(client *flashclient.FAClient) []SaveFunc {
	var exporters []SaveFunc
	exporters = append(exporters, ApiPathExporterFunc(client, "/active-directory", "active_directory.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/admins", "admins.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/admins/policies/management-access", "admins_policies_management_access.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/admins/api-tokens", "admins_api_tokens.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/admins/cache", "admins_cache.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/admins/settings", "admins_settings.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/alerts", "alerts.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/alerts/events", "alerts_events.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/alerts/rules", "alerts_rules.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/alerts/rules/catalog", "alerts_rules_catalog.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/alert-watchers", "alert_watchers.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/alert-watchers/test", "alert_watchers_test.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/api-clients", "api_clients.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/apps", "apps.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/apps/nodes", "apps_nodes.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/arrays", "arrays.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/arrays/cloud-config", "arrays_cloud_config.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/arrays/cloud-config/supported-configs", "arrays_cloud_config_supported_configs.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/arrays/cloud-capacity", "arrays_cloud_capacity.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/arrays/cloud-capacity/supported-steps", "arrays_cloud_capacity_supported_steps.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/arrays/cloud-provider-tags", "arrays_cloud_provider_tags.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/arrays/erasures", "arrays_erasures.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/arrays/eula", "arrays_eula.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/arrays/factory-reset-token", "arrays_factory_reset_token.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/arrays/ntp-test", "arrays_ntp_test.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/arrays/performance", "arrays_performance.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/arrays/performance/by-link", "arrays_performance_by_link.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/arrays/space", "arrays_space.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/arrays/tags", "arrays_tags.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/array-connections", "array_connections.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/array-connections/connection-key", "array_connections_connection_key.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/array-connections/path", "array_connections_path.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/audits", "audits.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/certificates", "certificates.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/certificates/certificate-groups", "certificates_certificate_groups.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/certificates/uses", "certificates_uses.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/certificate-groups", "certificate_groups.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/certificate-groups/certificates", "certificate_groups_certificates.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/certificate-groups/uses", "certificate_groups_uses.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/connections", "connections.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/container-default-protections", "container_default_protections.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/controllers", "controllers.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directories", "directories.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directories/groups", "directories_groups.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directories/performance", "directories_performance.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directories/policies", "directories_policies.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directories/policies/audit-file", "directories_policies_audit_file.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directories/policies/autodir", "directories_policies_autodir.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directories/policies/nfs", "directories_policies_nfs.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directories/policies/quota", "directories_policies_quota.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directories/policies/smb", "directories_policies_smb.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directories/policies/snapshot", "directories_policies_snapshot.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directories/policies/user-group-quota", "directories_policies_user_group_quota.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directories/space", "directories_space.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directories/users", "directories_users.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directory-exports", "directory_exports.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directory-group-quotas", "directory_group_quotas.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directory-quotas", "directory_quotas.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directory-services", "directory_services.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directory-services/roles", "directory_services_roles.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directory-services/roles/policies/management-access", "directory_services_roles_policies_management_access.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/directory-services/test", "directory_services_test.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directory-services/local/directory-services", "directory_services_local_directory_services.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directory-services/local/groups", "directory_services_local_groups.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directory-services/local/groups/members", "directory_services_local_groups_members.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directory-services/local/users", "directory_services_local_users.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directory-services/local/users/members", "directory_services_local_users_members.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directory-snapshots", "directory_snapshots.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/directory-user-quotas", "directory_user_quotas.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/dns", "dns.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/drives", "drives.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/file-systems", "file_systems.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/fleets", "fleets.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/fleets/fleet-key", "fleets_fleet_key.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/fleets/members", "fleets_members.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/hardware", "hardware.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/host-groups", "host_groups.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/host-groups/hosts", "host_groups_hosts.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/host-groups/performance", "host_groups_performance.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/host-groups/performance/by-array", "host_groups_performance_by_array.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/host-groups/protection-groups", "host_groups_protection_groups.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/host-groups/space", "host_groups_space.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/host-groups/tags", "host_groups_tags.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/hosts", "hosts.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/hosts/host-groups", "hosts_host_groups.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/hosts/performance", "hosts_performance.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/hosts/performance/balance", "hosts_performance_balance.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/hosts/performance/by-array", "hosts_performance_by_array.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/hosts/protection-groups", "hosts_protection_groups.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/hosts/space", "hosts_space.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/hosts/tags", "hosts_tags.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/kmip", "kmip.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/kmip/test", "kmip_test.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/log-targets", "log_targets.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/log-targets/file", "log_targets_file.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/log-targets/syslog", "log_targets_syslog.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/log-targets/syslog/settings", "log_targets_syslog_settings.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/log-targets/syslog/test", "log_targets_syslog_test.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/maintenance-windows", "maintenance_windows.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/network-interfaces", "network_interfaces.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/network-interfaces/neighbors", "network_interfaces_neighbors.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/network-interfaces/performance", "network_interfaces_performance.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/network-interfaces/port-details", "network_interfaces_port_details.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/offloads", "offloads.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/pods", "pods.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/pods/arrays", "pods_arrays.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/pods/members", "pods_members.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/pods/performance", "pods_performance.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/pods/performance/by-array", "pods_performance_by_array.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/pods/performance/replication", "pods_performance_replication.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/pods/performance/replication/by-array", "pods_performance_replication_by_array.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/pods/space", "pods_space.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/pods/tags", "pods_tags.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/pod-replica-links", "pod_replica_links.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/pod-replica-links/lag", "pod_replica_links_lag.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/pod-replica-links/performance/replication", "pod_replica_links_performance_replication.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/pod-replica-links/mappings/policies", "pod_replica_links_mappings_policies.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies", "policies.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/management-access", "policies_management_access.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/management-access/members", "policies_management_access_members.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/alert-watcher", "policies_alert_watcher.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/alert-watcher/members", "policies_alert_watcher_members.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/alert-watcher/rules", "policies_alert_watcher_rules.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/policies/alert-watcher/rules/test", "policies_alert_watcher_rules_test.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/audit-file", "policies_audit_file.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/audit-file/members", "policies_audit_file_members.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/autodir", "policies_autodir.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/autodir/members", "policies_autodir_members.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/members", "policies_members.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/nfs", "policies_nfs.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/nfs/client-rules", "policies_nfs_client_rules.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/nfs/members", "policies_nfs_members.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/password", "policies_password.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/quota", "policies_quota.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/quota/members", "policies_quota_members.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/quota/rules", "policies_quota_rules.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/smb", "policies_smb.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/smb/client-rules", "policies_smb_client_rules.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/smb/members", "policies_smb_members.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/snapshot", "policies_snapshot.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/snapshot/members", "policies_snapshot_members.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/snapshot/rules", "policies_snapshot_rules.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/user-group-quota", "policies_user_group_quota.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/user-group-quota/members", "policies_user_group_quota_members.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/policies/user-group-quota/rules", "policies_user_group_quota_rules.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/ports", "ports.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/ports/initiators", "ports_initiators.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/presets/workload", "presets_workload.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/protection-groups", "protection_groups.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/protection-groups/hosts", "protection_groups_hosts.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/protection-groups/host-groups", "protection_groups_host_groups.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/protection-groups/performance/replication", "protection_groups_performance_replication.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/protection-groups/performance/replication/by-array", "protection_groups_performance_replication_by_array.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/protection-groups/space", "protection_groups_space.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/protection-groups/tags", "protection_groups_tags.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/protection-groups/targets", "protection_groups_targets.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/protection-groups/volumes", "protection_groups_volumes.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/protection-group-snapshots", "protection_group_snapshots.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/protection-group-snapshots/tags", "protection_group_snapshots_tags.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/protection-group-snapshots/transfer", "protection_group_snapshots_transfer.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/realms", "realms.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/realms/performance", "realms_performance.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/realms/space", "realms_space.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/realms/tags", "realms_tags.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/remote-arrays", "remote_arrays.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/remote-pods", "remote_pods.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/remote-protection-groups", "remote_protection_groups.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/remote-protection-group-snapshots", "remote_protection_group_snapshots.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/remote-protection-group-snapshots/transfer", "remote_protection_group_snapshots_transfer.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/remote-volume-snapshots", "remote_volume_snapshots.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/remote-volume-snapshots/transfer", "remote_volume_snapshots_transfer.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/resource-accesses", "resource_accesses.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/resource-accesses/status", "resource_accesses_status.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/servers", "servers.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/sessions", "sessions.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/smi-s", "smi_s.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/smtp-servers", "smtp_servers.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/snmp-agents", "snmp_agents.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/snmp-agents/mib", "snmp_agents_mib.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/snmp-managers", "snmp_managers.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/snmp-managers/test", "snmp_managers_test.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/software", "software.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/software-bundle", "software_bundle.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/software-check", "software_check.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/software-installations", "software_installations.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/software-installation-steps", "software_installation_steps.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/software-patches", "software_patches.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/software-patches/catalog", "software_patches_catalog.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/software-versions", "software_versions.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/sso/saml2/idps", "sso_saml2_idps.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/sso/saml2/idps/test", "sso_saml2_idps_test.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/subnets", "subnets.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/subscriptions", "subscriptions.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/subscription-assets", "subscription_assets.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/support", "support.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/support/remote-assist-sessions", "support_remote_assist_sessions.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/support/remote-assist-sessions/settings", "support_remote_assist_sessions_settings.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/support/test", "support_test.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/support-diagnostics/details", "support_diagnostics_details.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/support-diagnostics/settings", "support_diagnostics_settings.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/syslog-servers", "syslog_servers.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/syslog-servers/settings", "syslog_servers_settings.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/syslog-servers/test", "syslog_servers_test.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/vchosts", "vchosts.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/vchosts/certificates", "vchosts_certificates.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/vchosts/endpoints", "vchosts_endpoints.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/vchost-connections", "vchost_connections.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/virtual-machines", "virtual_machines.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/virtual-machine-volume-snapshots", "virtual_machine_volume_snapshots.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/virtual-machine-snapshots", "virtual_machine_snapshots.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volumes", "volumes.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volumes/diff", "volumes_diff.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volumes/performance", "volumes_performance.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volumes/performance/by-array", "volumes_performance_by_array.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volumes/protection-groups", "volumes_protection_groups.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volumes/space", "volumes_space.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volumes/tags", "volumes_tags.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volumes/volume-groups", "volumes_volume_groups.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volume-groups", "volume_groups.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volume-groups/performance", "volume_groups_performance.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volume-groups/space", "volume_groups_space.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volume-groups/volumes", "volume_groups_volumes.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volume-groups/tags", "volume_groups_tags.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volume-snapshots", "volume_snapshots.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volume-snapshots/transfer", "volume_snapshots_transfer.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/volume-snapshots/tags", "volume_snapshots_tags.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/workloads/placement-recommendations", "workloads_placement_recommendations.json"))
	exporters = append(exporters, ApiPathExporterFunc(client, "/workloads", "workloads.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/workloads/tags", "workloads_tags.json"))
	return exporters
}

func ApiPathExporterFunc(client *flashclient.FAClient, apiPath string, fileName string) SaveFunc {
	if !strings.HasSuffix(fileName, ".json") {
		fileName += ".json"
	}
	return func(dir string) error {
		client.RefreshSession()

		var result any
		res, err := client.RestClient.R().
			SetResult(&result).
			Get(apiPath)
		if err != nil {
			return fmt.Errorf("failed to get API result for %s: %w", apiPath, err)
		} else if res.StatusCode() == http.StatusNotFound {
			return fmt.Errorf("API path %s not found (404): %w", apiPath, ErrExportOnInvalidPath)
		} else if res.StatusCode() != http.StatusOK {
			return fmt.Errorf("failed to get API result for %s, got status code %d", apiPath, res.StatusCode())
		}
		data, err := json.MarshalIndent(result, "", "  ")
		if err != nil {
			return fmt.Errorf("marshal %s: %w", fileName, err)
		}
		path := filepath.Join(dir, fileName)
		if err := os.WriteFile(path, data, 0644); err != nil {
			return fmt.Errorf("write result for %s: %w", fileName, err)
		}
		return nil
	}
}

func ExportArrayToDir(client *flashclient.FAClient, dirPath string) error {
	if err := os.MkdirAll(dirPath, 0755); err != nil {
		return fmt.Errorf("create output directory %s: %w", dirPath, err)
	}

	exporters := []SaveFunc{}

	versions, err := client.GetVersions()
	if err != nil {
		return fmt.Errorf("failed to get versions from client: %w", err)
	}
	exporters = append(exporters, VersionsSaveFunc("versions.json", versions))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/volumes", "volumes.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/volume-groups", "volume_groups.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/hosts", "hosts.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/host-groups", "host_groups.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/protection-groups", "protection_groups.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/protection-groups/hosts", "protection_groups_members_host.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/protection-groups/host-groups", "protection_groups_members_host_group.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/protection-groups/volumes", "protection_groups_members_volume.json"))
	// exporters = append(exporters, ApiPathExporterFunc(client, "/pods", "pods.json"))

	exporters = append(exporters, allExporters(client)...)

	for _, exporter := range exporters {
		err := exporter(dirPath)
		if errors.Is(err, ErrExportOnInvalidPath) {
			fmt.Printf("Warning: %v\n", err)
		} else if err != nil {
			fmt.Printf("Warning: %v\n", err)
			// return err
		}
	}

	return nil
}
