package flashclient

import (
	"fmt"
	"net/http"
	"strings"
)

type VolumeSnapshot struct {

	// A globally unique, system-generated ID. The ID cannot be modified and cannot refer to another resource.
	Id string `json:"id,omitempty"`

	// A user-specified name. The name must be locally unique and can be changed.
	Name string `json:"name,omitempty"`

	// The snapshot creation time. Measured in milliseconds since the UNIX epoch.
	Created int64 `json:"created,omitempty"`

	// Returns a value of `true` if the snapshot has been destroyed and is pending eradication. The `time_remaining` value displays the amount of time left until the destroyed volume snapshot is permanently eradicated. Before the `time_remaining` period has elapsed, the destroyed volume snapshot can be recovered by setting `destroyed=false`. Once the `time_remaining` period has elapsed, the volume snapshot is permanently eradicated and can no longer be recovered.
	Destroyed bool `json:"destroyed,omitempty"`

	// A reference to the pod.
	Pod FixedReference `json:"pod,omitempty"`

	// The provisioned space of the snapshot. Measured in bytes. The minimum size is 1048576 (1MB), the maximum size is 4503599627370496 (4PB)
	Provisioned int64 `json:"provisioned,omitempty"`

	// The volume from which this snapshot was taken. For a replicated snapshot being viewed on the target side, the `source` is the replica volume.
	Source Source `json:"source,omitempty"`

	// The suffix that is appended to the `source_name` value to generate the full volume snapshot name in the form `VOL.SUFFIX`. If the suffix is not specified, the system constructs the snapshot name in the form `VOL.NNN`, where `VOL` is the volume name, and `NNN` is a monotonically increasing number.
	Suffix string `json:"suffix,omitempty"`

	// The amount of time left until the destroyed snapshot is permanently eradicated. Measured in milliseconds. Before the `time_remaining` period has elapsed, the destroyed snapshot can be recovered by setting `destroyed=false`.
	TimeRemaining int64 `json:"time_remaining,omitempty"`

	// The context in which the operation was performed. Valid values include a reference to any array which is a member of the same fleet. If the array is not a member of a fleet, `context` will always implicitly be set to the array that received the request.  Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided `context`.
	Context FixedReference `json:"context,omitempty"`

	// A serial number generated by the system when the snapshot is created. The serial number is unique across all arrays.
	Serial string `json:"serial,omitempty"`

	// Displays size and space consumption information.
	Space SnapshotSpace `json:"space,omitempty"`

	// The volume group to which the volume that is the source of the volume snapshot belongs.
	VolumeGroup FixedReference `json:"volume_group,omitempty"`
}

type SnapshotSpace struct {

	// The ratio of mapped sectors within a volume versus the amount of physical space the data occupies after data compression and deduplication. The data reduction ratio does not include thin provisioning savings. For example, a data reduction ratio of 5&#58;1 means that for every 5 MB the host writes to the array, 1 MB is stored on the array's flash modules.
	DataReduction float32 `json:"data_reduction,omitempty"`

	// The maximum amount of physical space the container consumes on an array, ignoring any data shared outside the container, measured in bytes. On Evergreen//One arrays, this is the maximum amount of effective used space. The footprint metric is mostly used for capacity planning. This field will be null in non-container contexts.
	Footprint int64 `json:"footprint,omitempty"`

	// The physical space occupied by deduplicated data, meaning that the space is shared with other volumes and snapshots as a result of data deduplication. Measured in bytes. On Evergreen//One arrays, this is the effective space contributed by data that is not unique to a specific volume, managed directory, or snapshot, measured in bytes.
	Shared int64 `json:"shared,omitempty"`

	// The physical space occupied by data unique to one or more snapshots. Measured in bytes. On Evergreen//One arrays, this is the effective space contributed by data unique to one or more snapshots, measured in bytes.
	Snapshots int64 `json:"snapshots,omitempty"`

	// The physical space occupied by internal array metadata. Measured in bytes.
	System int64 `json:"system,omitempty"`

	// The percentage of volume sectors that do not contain host-written data because the hosts have not written data to them or the sectors have been explicitly trimmed.
	ThinProvisioning float32 `json:"thin_provisioning,omitempty"`

	// This field has been deprecated. Use the `total_used` field, as it contains the same information.
	TotalPhysical int64 `json:"total_physical,omitempty"`

	// The provisioned size of a volume for a single volume, host or host group, protocol endpoint, managed directory, and containers can be infinite or measured in bytes. Infinite is represented by `null`. The provisioned size for a host or host group, includes all volumes that are connected to the resource. The provisioned size for a protocol endpoint is `null'. The provisioned size for a managed directory is the quota limit if it or its parent has a managed directory configured, otherwise it defaults to `null`. The provisioned size for a container is the sum of the total_provisioned of the object it contains, capped by the container's quota limit (or the container's used_provisioned if current usage is above the quota limit), if any. Provisioned size represents the storage capacity reported to hosts.
	TotalProvisioned int64 `json:"total_provisioned,omitempty"`

	// The ratio of provisioned sectors within a volume versus the amount of physical space the data occupies after reduction via data compression and deduplication and with thin provisioning savings. Total reduction is data reduction with thin provisioning savings. For example, a total reduction ratio of 10&#58;1 means that for every 10 MB of provisioned space, 1 MB is stored on the array's flash modules.
	TotalReduction float32 `json:"total_reduction,omitempty"`

	// The total space contributed by customer data, measured in bytes.
	TotalUsed int64 `json:"total_used,omitempty"`

	// The unique physical space occupied by customer data. Unique physical space does not include shared space, snapshots, and internal array metadata. Measured in bytes. On Evergreen//One arrays, this is the effective space contributed by unique customer data, measured in bytes. Unique data does not include shared space, snapshots, and internal array metadata.
	Unique int64 `json:"unique,omitempty"`

	// The amount of logical space a container has consumed, compared against the quota limit if the container has one configured. Used provisioned does not include destroyed objects inside the container. Used provisioned can include destroyed objects for a destroyed container and represents how much logical space it would take to recover the container.
	UsedProvisioned int64 `json:"used_provisioned,omitempty"`

	// The amount of logically written data that a volume or a snapshot references. Measured in bytes.
	Virtual int64 `json:"virtual,omitempty"`

	// This field has been deprecated. The effective space contributed by data unique to one or more snapshots, measured in bytes. Use the `snapshots` field in the future, as it contains the same information for Evergreen//One arrays.
	SnapshotsEffective int64 `json:"snapshots_effective,omitempty"`
}

type VolumeSnapshotPostBody struct {
	// If set to `true`, destroys a resource. Once set to `true`,
	// the `time_remaining` value will display the amount of time left
	// until the destroyed resource is permanently eradicated.
	// Before the `time_remaining` period has elapsed, the destroyed resource
	// can be recovered by setting `destroyed=false`.
	// Once the `time_remaining` period has elapsed,
	// the resource is permanently eradicated and can no longer be recovered.
	Destroyed *bool `json:"destroyed,omitempty"`

	// The suffix that is appended to the `source_name` value and the `client_name` value to
	// generate the full directory snapshot name in the form of `DIR.CLIENT_NAME.SUFFIX` where
	// `DIR` is the managed directory name, `CLIENT_NAME` is the client name, and `SUFFIX` is
	// the suffix. If the suffix is a string, this field returns `null`. See the `name` value
	// for the full snapshot name including the suffix.
	Suffix *string `json:"suffix,omitempty"`
}

type VolumeSnapshotPatchBody struct {
	// If set to `true`, destroys a resource. Once set to `true`,
	// the `time_remaining` value will display the amount of time left
	// until the destroyed resource is permanently eradicated.
	// Before the `time_remaining` period has elapsed, the destroyed resource
	// can be recovered by setting `destroyed=false`.
	// Once the `time_remaining` period has elapsed,
	// the resource is permanently eradicated and can no longer be recovered.
	Destroyed *bool `json:"destroyed,omitempty"`

	// THe new name for the Volume Snapshot
	Name *string `json:"name,omitempty"`
}

func (fa *FAClient) GetVolumeSnapshots() ([]VolumeSnapshot, error) {
	err := fa.RefreshSession()
	if err != nil {
		return nil, fmt.Errorf("failed to refresh session: %v", err)
	}

	uri := "/volume-snapshots"
	result := Results[VolumeSnapshot]{}
	res, err := fa.RestClient.R().
		SetResult(&result).
		Get(uri)
	if err != nil {
		return nil, err
	} else if res.StatusCode() != 200 {
		return nil, fmt.Errorf("failed to get volume snapshots, got status code %d", res.StatusCode())
	}
	return result.Items, nil
}

func (fa *FAClient) GetVolumeSnapshotsForVolume(volumeIds ...string) ([]VolumeSnapshot, error) {
	err := fa.RefreshSession()
	if err != nil {
		return nil, fmt.Errorf("failed to refresh session: %v", err)
	}

	uri := "/volume-snapshots"
	result := Results[VolumeSnapshot]{}
	res, err := fa.RestClient.R().
		SetResult(&result).
		SetQueryParam("source_ids", strings.Join(volumeIds, ",")).
		Get(uri)
	if err != nil {
		return nil, err
	} else if res.StatusCode() != 200 {
		return nil, fmt.Errorf("failed to get volume snapshots, got status code %d", res.StatusCode())
	}
	return result.Items, nil
}

func (fa *FAClient) GetVolumeSnapshot(snapshotId string) (*VolumeSnapshot, error) {
	err := fa.RefreshSession()
	if err != nil {
		return nil, fmt.Errorf("failed to refresh session: %v", err)
	}

	uri := "/volume-snapshots"
	result := Results[VolumeSnapshot]{}
	res, err := fa.RestClient.R().
		SetResult(&result).
		SetQueryParam("ids", snapshotId).
		Get(uri)
	if err != nil {
		return nil, err
	} else if res.StatusCode() != 200 {
		return nil, fmt.Errorf("failed to get volume snapshots, got status code %d", res.StatusCode())
	}
	if len(result.Items) == 0 {
		return nil, fmt.Errorf("volume snapshot with ID %s not found", snapshotId)
	}
	return &result.Items[0], nil
}

func (fa *FAClient) GetVolumeSnapshotByName(snapshotName string) (*VolumeSnapshot, error) {
	err := fa.RefreshSession()
	if err != nil {
		return nil, fmt.Errorf("failed to refresh session: %v", err)
	}

	uri := "/volume-snapshots"
	result := Results[VolumeSnapshot]{}
	res, err := fa.RestClient.R().
		SetResult(&result).
		SetQueryParam("names", snapshotName).
		Get(uri)
	if err != nil {
		return nil, err
	} else if res.StatusCode() != http.StatusOK {
		return nil, fmt.Errorf("failed to get volume snapshots, got status code %d", res.StatusCode())
	}
	if len(result.Items) == 0 {
		return nil, fmt.Errorf("volume snapshot with name %s not found", snapshotName)
	}
	return &result.Items[0], nil
}

func (fa *FAClient) CreateVolumeSnapshot(volumeId string, snapshotPost VolumeSnapshotPostBody) (*VolumeSnapshot, error) {
	err := fa.RefreshSession()
	if err != nil {
		return nil, fmt.Errorf("failed to refresh session: %v", err)
	}

	uri := "/volume-snapshots"
	result := Results[VolumeSnapshot]{}
	res, err := fa.RestClient.R().
		SetBody(snapshotPost).
		SetQueryParam("source_ids", volumeId).
		SetResult(&result).
		Post(uri)
	if err != nil {
		return nil, err
	} else if res.StatusCode() != http.StatusOK {
		return nil, fmt.Errorf("failed to create volume snapshot, got status code %d", res.StatusCode())
	}
	if len(result.Items) == 0 {
		return nil, fmt.Errorf("failed to create volume snapshot, no snapshot returned")
	}
	return &result.Items[0], nil
}

func (fa *FAClient) UpdateVolumeSnapshot(snapshotId string, snapshotPatch VolumeSnapshotPatchBody) (*VolumeSnapshot, error) {
	err := fa.RefreshSession()
	if err != nil {
		return nil, fmt.Errorf("failed to refresh session: %v", err)
	}

	uri := "/volume-snapshots"
	result := Results[VolumeSnapshot]{}
	res, err := fa.RestClient.R().
		SetBody(snapshotPatch).
		SetQueryParam("ids", snapshotId).
		SetResult(&result).
		Patch(uri)
	if err != nil {
		return nil, err
	} else if res.StatusCode() != http.StatusOK {
		return nil, fmt.Errorf("failed to update volume snapshot, got status code %d", res.StatusCode())
	}
	if len(result.Items) == 0 {
		return nil, fmt.Errorf("failed to update volume snapshot, no snapshot returned")
	}
	return &result.Items[0], nil
}

func (fa *FAClient) DestroyVolumeSnapshot(snapshotId string) error {
	_, err := fa.UpdateVolumeSnapshot(snapshotId, VolumeSnapshotPatchBody{Destroyed: toPtr(true)})
	if err != nil {
		return fmt.Errorf("failed to destroy volume snapshot: %v", err)
	}

	return nil
}

func (fa *FAClient) EradicateVolumeSnapshot(snapshotId string) error {
	err := fa.RefreshSession()
	if err != nil {
		return fmt.Errorf("failed to refresh session: %v", err)
	}

	uri := "/volume-snapshots"
	res, err := fa.RestClient.R().
		SetQueryParam("ids", snapshotId).
		Delete(uri)
	if err != nil {
		return err
	} else if res.StatusCode() != http.StatusOK {
		return fmt.Errorf("failed to eradicate volume snapshot, got status code %d", res.StatusCode())
	}
	return nil
}
